### ISSUE TITLE
Compile Error on gcc 4.8.5

### ISSUE THREAD

**Issue by sfd1v** [JacksonAllan/Verstable#3]
```
#include <stdio.h>

#define NAME int_int_map
#define KEY_TY int 
#define VAL_TY int  
#include "verstable.h"

int main(int argc, char const *argv[])
{
    int_int_map htable;
    vt_init(&htable);

    return 0;
}
```

```
[root@DESKTOP-OAKHD5F src]# gcc -std=c11 main.c 
In file included from main.c:6:0:
verstable.h: In function ‘int_int_map_evict’:
verstable.h:894:3: warning: implicit declaration of function ‘_Generic’ [-Wimplicit-function-declaration]
   size_t home_bucket = HASH_FN( table->buckets[ bucket ].key ) & ( table->bucket_count - 1 );
   ^
verstable.h:763:44: error: expected expression before ‘char’
 #define HASH_FN _Generic( ( KEY_TY ){ 0 }, char *: vt_hash_string, default: vt_hash_integer )
                                            ^
verstable.h:894:24: note: in expansion of macro ‘HASH_FN’
   size_t home_bucket = HASH_FN( table->buckets[ bucket ].key ) & ( table->bucket_count - 1 );
                        ^
verstable.h: In function ‘int_int_map_insert_raw’:
verstable.h:763:44: error: expected expression before ‘char’
 #define HASH_FN _Generic( ( KEY_TY ){ 0 }, char *: vt_hash_string, default: vt_hash_integer )
                                            ^
verstable.h:966:19: note: in expansion of macro ‘HASH_FN’
   uint64_t hash = HASH_FN( key );
                   ^
verstable.h:772:44: error: expected expression before ‘char’
 #define CMPR_FN _Generic( ( KEY_TY ){ 0 }, char *: vt_cmpr_string, default: vt_cmpr_integer )
                                            ^
verstable.h:1007:9: note: in expansion of macro ‘CMPR_FN’
         CMPR_FN( table->buckets[ bucket ].key, key )
         ^
verstable.h: In function ‘int_int_map_get’:
verstable.h:763:44: error: expected expression before ‘char’
 #define HASH_FN _Generic( ( KEY_TY ){ 0 }, char *: vt_hash_string, default: vt_hash_integer )
                                            ^
verstable.h:1209:19: note: in expansion of macro ‘HASH_FN’
   uint64_t hash = HASH_FN( key );
                   ^
verstable.h:772:44: error: expected expression before ‘char’
 #define CMPR_FN _Generic( ( KEY_TY ){ 0 }, char *: vt_cmpr_string, default: vt_cmpr_integer )
                                            ^
verstable.h:1221:74: note: in expansion of macro ‘CMPR_FN’
     if( ( table->metadata[ bucket ] & VT_HASH_FRAG_MASK ) == hashfrag && CMPR_FN( table->buckets[ bucket ].key, key ) )
                                                                          ^
verstable.h: In function ‘int_int_map_erase_itr_raw’:
verstable.h:763:44: error: expected expression before ‘char’
 #define HASH_FN _Generic( ( KEY_TY ){ 0 }, char *: vt_hash_string, default: vt_hash_integer )
                                            ^
verstable.h:1277:25: note: in expansion of macro ‘HASH_FN’
       itr.home_bucket = HASH_FN( table->buckets[ itr_bucket ].key ) & ( table->bucket_count - 1 );
                         ^
In file included from main.c:6:0:
main.c: In function ‘main’:
verstable.h:579:65: error: expected expression before ‘vt_table_0000’
 #define vt_init( table ) _Generic( *( table ) VT_GENERIC_SLOTS( vt_table_, vt_init_ ) )( table )
                                                                 ^
verstable.h:405:25: note: in definition of macro ‘VT_CAT_’
 #define VT_CAT_( a, b ) a##b
                         ^
verstable.h:544:40: note: in expansion of macro ‘VT_CAT’
 #define VT_GENERIC_SLOT( ty, fn, n ) , VT_CAT( ty, n ): VT_CAT( fn, n )
                                        ^
verstable.h:546:35: note: in expansion of macro ‘VT_GENERIC_SLOT’
 #define VT_R1_1( ty, fn, d3, d2 ) VT_GENERIC_SLOT( ty, fn, VT_CAT_4( 0, d3, d2, 0 ) )
                                   ^
verstable.h:405:25: note: in expansion of macro ‘VT_R1_1’
 #define VT_CAT_( a, b ) a##b
                         ^
verstable.h:579:47: note: in expansion of macro ‘VT_GENERIC_SLOTS’
 #define vt_init( table ) _Generic( *( table ) VT_GENERIC_SLOTS( vt_table_, vt_init_ ) )( table )
                                               ^
main.c:13:5: note: in expansion of macro ‘vt_init’
     vt_init(&flow_table);
     ^
```

```
[root@DESKTOP-OAKHD5F src]# gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by JacksonAllan** [comment]
You can set `-std=c11` on GCC 4.8.5, but full support for C11—including `_Generic`—[only came in 4.9.0](https://gcc.gnu.org/wiki/C11Status). Hence, you have two options:

* Upgrade to GCC 4.9.0 or later.

* Using the C99 prefixed function API instead of the C11 generic macro API. The C99 has two major differences. Firstly, you [must explicitly define hash and comparison functions](https://github.com/JacksonAllan/Verstable/blob/main/api_reference.md#:~:text=In%20C99%2C%20it%20is%20also%20always%20necessary%20to%20define%20HASH_FN%20and%20CMPR_FN%20(see%20below)%20before%20including%20the%20header.) for all types, including integer types and strings. The easiest solution is to just use the default functions provided by the library: `vt_hash_integer` and `vt_cmpr_integer` for all integer types and `vt_hash_string` and `vt_cmpr_string` for strings. Secondly, instead of prefixing API calls with `vt_`, prefix them with [the name of your hash-table type](https://github.com/JacksonAllan/Verstable/blob/main/api_reference.md#:~:text=The%20functions%20associated%20with%20a%20hash%20table%20type%20are%20all%20prefixed%20with%20the%20name%20the%20user%20supplied%20via%20the%20NAME%20macro.%0AIn%20C11%20and%20later%2C%20the%20generic%20vt_%2Dprefixed%20macros%20may%20be%20used%20to%20automatically%20select%20the%20correct%20version%20of%20the%20specified%20function%20based%20on%20the%20arguments.).

  [Here](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1AB9U8lJL6yAngGVG6AMKpaAVxYMJATlIOAMngMmABy7gBGmMQSAMykAA6oCoS2DM5uHt7xickCAUGhLBFRXLGWmNYpQgRMxARp7p5cPmUVAlU1BHkh4ZExFtW19RlN/R1dBUUxAJQWqK7EyOwcAKQATNGByG5YANTL0Y4KBPioAHQI%2B9jLGgCC1zcA9A87AJIMR4Y2TDZGO0w7SgIOwImBYcQMINO9zW0SwNCCO2CNwAstgdoECMZAdD1nDApgdgBpbAATWMABUSejBDjYZh4QSABI3ISM4wAMWCOwAbpiEEwFAhjBjMMBIrS8QjHMjlAAlDlc3nGZBg4jCwSi8W3GGbbYE/aOBAEAhxBQgJ7EJgAd1OwEICFcYVcSgWskYBFOaBYDwAUkxkABrBQCG60AwMB4ANUiHzC9AeLCYgQe3Jj1TjmHOl2htyer3e1UEeG%2BgWAfx2ibiwNB4O%2BmYl9PxiJRaIx6sxlYbDKJpIpVIxXabkZufj71IIg4RzNZCp5fIFQpFYuIk4J0rls6VKriaqXWru611rl2BqNJrNFuttvtjudkTQGsEntQ3r9geDDFD4ajaaYGYTSYRqmxCxvQWbRFc2q3BiFaARAPKoHg6A7FM0IAOwAEL3DsOx5kImAejmNw4W2gI7HMarYtEWG3CRghYgR6qEPBawAGwUQxQKodRRE4Xmbwuj8ZYBpgACeChQrROz8MQ8EwXgezRAAIjsGj7Bh6KKY4OxcGp1F7KsWGGQpqFScsmHYTh46ccKBDEOidmKSppGMYEgksas7HzJxpCadxNHEVZeBUHJ9GAsKCjGA4cmOVMKGWVZOyYKozE6fF%2Bl5gA8q4QKoFQFagiQomSYF5lKbxuHPNglpJL8IniSVOEyaFQIKfsKl6RpbUHDpnWaWsWHKTs0TxVJdGYuFkQCpgHleZRBG%2BSZ6kVXmsoEcQeCYNypY7PVEmWc1479UNfXddpunqQZRkYUtZkWWN1nhYQ9nPU5j2MWKBCzRxgKLelAWJcF8FgGALmYngkXRQ59lxaZgWJTuGIhQZqxrAArMhayrItdmnOg3xMAAtJc9X/ZZZWWXmygbRq6AgGlqw7JIOxozsaE7AAHCtzwvCClo2AIjXSSQEAJe94OOa97Xi8YNAgV9BlzZxZMPSDYMRVFDDoDFMPLQ9UtDerQSqArr1wzh5tWYjgjI1j6OY6s2PQ3jBPExBpP%2BZTzzUyKdNMyzOyMxzaVoRV6tbJghiuHE33eWRntQYFebIkwcQlZZbZtpW5HeZ2PFSZn9GVkxCtsRx2cJ3cUn8e8kRCbtYkKH8Ws8mIriYPtUmHfJb2nVpvWXQNA23aV93w9ZWep7ZL2OdLhcdlPbl17HaqVotf0DWlleA8j8/GMXEOa9r0MoaN484clqVcP9lU7NluX5WwLBFULFOJ3xVU1Tte3N8h3Jtx3IW3dBDHQ6pdM6A99JtUMtLEaltxrtn3lPKaSgV5ILiH9SuXsdhrTsptbadVG6/1bm4QBB0RZHW6mAqB/cLr6SHsZM%2BOFzIAyCvRSecRp4nznuwouU9PpoLXn5PW48gY7DVrwhenDD5QzNkwxKOxrYEBCmLZhGgvB21WBjEA9sUakFUXsdRz0XbVDdtgeq%2BiHpqK8MY/GpjLj/1oGLbeew0LlWrt7GmII/ZcBAIzVYIARqSBAKzNGIBWJsxAMHDmIANHv1vrzKaAsGBAJFmLPeB9Jaz0NpI9Bss8Dy0EanFW48JHgz4dIyGWsdYlMBtk5yuTi7G1NrFSy8DFFeJUVYlG9sdFaIdtjAxtjXYkzEpY8%2Bzs7FEwcWIZxIiP47B9rTemwTQnhMDoEzmsSdJ%2BMiVzeJGSp4RyjjHRW5dilYLcfcDgMxaCcDRrwTwHAtCkFQJwbSwZ5iLAMtEHgpACCaBuTMBAkcsBRAgDMAMISvCnGiBoX50Q0Yc2RWjDQXA0LSDuRwSQjzAWvM4LwM0Gh/mApmHAWASBkrlByiQcglAajAAUMoQwmBaBCAQKgK0Ty/lejiHQEsAhmVBDZRyrleLeV0F6MgYAkgOZo1IBK%2BgxBgisCWLwRVkR77ss5U8l5VLkA3GIIyglvhVDlCqPgJ5vB%2BCCBEGIdgUgZCCEUCodQzydB6HDCYMw%2Bg8BhDNJAGYqA4jJLNBwQmRx0DtWQFwP5qBgIbSwAGiFpBiCuCLGwckqAXDJpmJ8hYDr%2BiWqFay7VYruC8DspgJYfyrSWjiJwHgtz7m4vdfijg2AzXIBpfZVQHNWKE1YszYAyBkBM1OBzU4rMICOF8rgQgJAflcCmJW0lwLQW9BTVCyQGhTisS8KxftkhY1SC8BzTy%2BhOA4tILq3gbyOCEpAMSgF7qpjNo4KsVtLz72rtfTMYCSQ7CSCAA%3D%3D) is an example.
